#!/usr/bin/php

<?php

$globalAutoloadPath = __DIR__ . '/../../../autoload.php';
$projectAutoloadPath = __DIR__ . '/../vendor/autoload.php';
if (file_exists($globalAutoloadPath)) {
    require_once $globalAutoloadPath;
} else {
    require_once $projectAutoloadPath;
}

use function BrainGames\Cli\sayWelcome;
use function BrainGames\Cli\sayCongratulations;
use function BrainGames\Games\printGame;

sayWelcome("Answer \"yes\" if the number is even, otherwise answer \"no\".");
printGame("even");
sayCongratulations();